### ISSUE TITLE
Crash after opening exe file

### ISSUE THREAD

**Issue by annaoliver** [ashapsoncoe/CREST#6]
It crashes when I open the CREST_v1.0.exe file：
Traceback (most recent call last):
  File "CREST_v0.24.py", line 4211, in <module>
  File "CREST_v0.24.py", line 96, in __init__
  File "CREST_v0.24.py", line 265, in make_labels_and_entries
  File "CREST_v0.24.py", line 709, in update_selected_db
  File "CREST_v0.24.py", line 549, in get_segs_and_layers
sqlite3.OperationalError: no such table: unique_seg_regions_table
[18836] Failed to execute script 'CREST_v0.24' due to unhandled exception!

**Comment by annaoliver** [comment]
sorry，My problem is solved. It's because I changed the name of the db file.
